repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.3
    hooks:
      - id: clang-format
        types_or: [c++, c]

  - repo: https://github.com/BlankSpruce/gersemi
    rev: 0.27.0
    hooks:
      - id: gersemi

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.10
    hooks:
      - id: commitizen
        stages: [commit-msg]
